[2025-02-04 15:23:01,941] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: grippe_etl_pipeline.fetch_grippe_data manual__2025-02-04T15:23:01.731636+00:00 [queued]>
[2025-02-04 15:23:01,944] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: grippe_etl_pipeline.fetch_grippe_data manual__2025-02-04T15:23:01.731636+00:00 [queued]>
[2025-02-04 15:23:01,944] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-04 15:23:01,944] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-02-04 15:23:01,944] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-04 15:23:01,948] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): fetch_grippe_data> on 2025-02-04 15:23:01.731636+00:00
[2025-02-04 15:23:01,950] {standard_task_runner.py:52} INFO - Started process 1713 to run task
[2025-02-04 15:23:01,951] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'grippe_etl_pipeline', 'fetch_grippe_data', 'manual__2025-02-04T15:23:01.731636+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/influenza-ETL.py', '--cfg-path', '/tmp/tmp1rhdcj7z', '--error-file', '/tmp/tmpzknkrcqn']
[2025-02-04 15:23:01,952] {standard_task_runner.py:80} INFO - Job 376: Subtask fetch_grippe_data
[2025-02-04 15:23:01,968] {task_command.py:370} INFO - Running <TaskInstance: grippe_etl_pipeline.fetch_grippe_data manual__2025-02-04T15:23:01.731636+00:00 [running]> on host 559b3591b7a4
[2025-02-04 15:23:01,990] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=grippe_etl_pipeline
AIRFLOW_CTX_TASK_ID=fetch_grippe_data
AIRFLOW_CTX_EXECUTION_DATE=2025-02-04T15:23:01.731636+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-04T15:23:01.731636+00:00
[2025-02-04 15:23:02,221] {python.py:173} INFO - Done. Returned value was: Empty DataFrame
Columns: []
Index: []
[2025-02-04 15:23:02,230] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2025-02-04 15:23:02,230] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2392, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2025-02-04 15:23:02,236] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=grippe_etl_pipeline, task_id=fetch_grippe_data, execution_date=20250204T152301, start_date=20250204T152301, end_date=20250204T152302
[2025-02-04 15:23:02,243] {standard_task_runner.py:97} ERROR - Failed to execute job 376 for task fetch_grippe_data (Object of type DataFrame is not JSON serializable; 1713)
[2025-02-04 15:23:02,253] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-02-04 15:23:02,272] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
