[2025-02-05 13:14:09,413] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: grippe_ETL_pipeline.load_vaccins manual__2025-02-05T13:14:06.531755+00:00 [queued]>
[2025-02-05 13:14:09,416] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: grippe_ETL_pipeline.load_vaccins manual__2025-02-05T13:14:06.531755+00:00 [queued]>
[2025-02-05 13:14:09,417] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-02-05 13:14:09,417] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2025-02-05 13:14:09,417] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-02-05 13:14:09,421] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_vaccins> on 2025-02-05 13:14:06.531755+00:00
[2025-02-05 13:14:09,423] {standard_task_runner.py:52} INFO - Started process 8266 to run task
[2025-02-05 13:14:09,424] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'grippe_ETL_pipeline', 'load_vaccins', 'manual__2025-02-05T13:14:06.531755+00:00', '--job-id', '616', '--raw', '--subdir', 'DAGS_FOLDER/influenza-ETL.py', '--cfg-path', '/tmp/tmpb13wibu9', '--error-file', '/tmp/tmp_8n9e4xg']
[2025-02-05 13:14:09,425] {standard_task_runner.py:80} INFO - Job 616: Subtask load_vaccins
[2025-02-05 13:14:09,447] {task_command.py:370} INFO - Running <TaskInstance: grippe_ETL_pipeline.load_vaccins manual__2025-02-05T13:14:06.531755+00:00 [running]> on host e70e045b31e0
[2025-02-05 13:14:09,473] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=grippe_ETL_pipeline
AIRFLOW_CTX_TASK_ID=load_vaccins
AIRFLOW_CTX_EXECUTION_DATE=2025-02-05T13:14:06.531755+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-05T13:14:06.531755+00:00
[2025-02-05 13:14:10,961] {logging_mixin.py:115} INFO - ✅ Chargement réussi dans la table grippe_vaccins (52 lignes)
[2025-02-05 13:14:10,962] {python.py:173} INFO - Done. Returned value was: None
[2025-02-05 13:14:10,984] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=grippe_ETL_pipeline, task_id=load_vaccins, execution_date=20250205T131406, start_date=20250205T131409, end_date=20250205T131410
[2025-02-05 13:14:11,033] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-05 13:14:11,051] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
